name = "training-partner-app"
main = "worker/index.js"
compatibility_date = "2026-03-09"
workers_dev = true

[vars]
FRONTEND_URL = "https://training-partner.vercel.app"

[[d1_databases]]
binding = "DB"
database_name = "training-partner"
database_id = "30d075cd-2994-4d08-8aef-7ed1a415d9bb"
migrations_dir = "./migrations"
